RTLOGGERSERVER:
  port : 12000
  instanceCount: 4

  jtLoggerOptions: 
    type: 'rotating-file'
    level: 'info'
    period: '600000ms'
    count: 7
    path: '/Users/balwinderkatoch/bk/logs/rt-log.log'
  serverLoggerOptions: 
    type: 'rotating-file'
    level: 'info'
    period: '1d'
    count: 7
    path: '/Users/balwinderkatoch/bk/logs/server-log.log'